/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaria.interfaces;

import controller.ListaIngredientes;
import controller.ListaPizzas;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import pizzaria.classes.Funcionarios;
import pizzaria.classes.Gerente;
import pizzaria.classes.Ingredientes;
import pizzaria.classes.Pizzas;

/**
 *
 * @author usuario
 */
public class interface_cozinha extends javax.swing.JFrame {

    /**
     * Creates new form interface_cozinha
     */
    private ListaPizzas pizzas = new ListaPizzas();
    private ListaIngredientes ingredientes = new ListaIngredientes();

    public interface_cozinha() {
        initComponents();
        setLocationRelativeTo(null);
        adicionarPizzas();
        adicionarIngredientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pizza_logopequena = new javax.swing.JLabel();
        b_retornar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPizzas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        titulo_listapizzas = new javax.swing.JLabel();
        titulo_listaingredientes = new javax.swing.JLabel();
        pizza_fachada1 = new javax.swing.JLabel();
        pizza_fachada2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 0, 0));

        pizza_logopequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/pizza_logo_pequena.png"))); // NOI18N

        b_retornar.setBackground(new java.awt.Color(85, 0, 0));
        b_retornar.setForeground(new java.awt.Color(245, 239, 239));
        b_retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/saida.png"))); // NOI18N
        b_retornar.setBorderPainted(false);
        b_retornar.setFocusPainted(false);
        b_retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retornarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(147, 26, 37));

        tabelaPizzas.setBackground(new java.awt.Color(245, 239, 239));
        tabelaPizzas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaPizzas.setForeground(new java.awt.Color(0, 0, 0));
        tabelaPizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Valor ( Média <15>)"
            }
        ));
        tabelaPizzas.setRowHeight(50);
        jScrollPane2.setViewportView(tabelaPizzas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(147, 26, 37));

        jTable3.setBackground(new java.awt.Color(245, 239, 239));
        jTable3.setForeground(new java.awt.Color(0, 0, 0));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Valor"
            }
        ));
        jTable3.setRowHeight(30);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo_listapizzas.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        titulo_listapizzas.setForeground(new java.awt.Color(245, 239, 239));
        titulo_listapizzas.setText("Pizzas Disponíveis:");

        titulo_listaingredientes.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        titulo_listaingredientes.setForeground(new java.awt.Color(245, 239, 239));
        titulo_listaingredientes.setText("Ingredientes no Estoque:");

        pizza_fachada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/pizza4.png"))); // NOI18N

        pizza_fachada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/tempero4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(pizza_fachada1)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pizza_fachada2)
                        .addGap(90, 90, 90)
                        .addComponent(b_retornar)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(86, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(titulo_listapizzas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_listaingredientes)
                .addGap(43, 43, 43)
                .addComponent(pizza_logopequena)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizza_logopequena)
                    .addComponent(titulo_listapizzas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulo_listaingredientes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 658, Short.MAX_VALUE)
                        .addComponent(b_retornar)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pizza_fachada2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pizza_fachada1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retornarActionPerformed
        interface_areaFuncionarios i_areaFuncionarios = new interface_areaFuncionarios();
        i_areaFuncionarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_retornarActionPerformed

    private void listarPizzas() {

        ArrayList nomeColunas = new ArrayList();
        nomeColunas.add("Nome");
        nomeColunas.add("Valor (Media <15>) ");

        List<Object[]> dados = new ArrayList<>();

        for (Pizzas pizzas : pizzas.getListaPizzas()) {

            List dadosCli = new ArrayList();
            dadosCli.add(pizzas.getNome());
            NumberFormat formatador = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            dadosCli.add(formatador.format(pizzas.getValor()));

            dados.add(dadosCli.toArray());

        }

        DefaultTableModel tabelaDefault = new DefaultTableModel(dados.toArray(new Object[dados.size()][]), nomeColunas.toArray());
        tabelaPizzas.setModel(tabelaDefault);
    }

    private void adicionarPizzas() {
        Pizzas Margherita = new Pizzas("Margherita", 52);
        pizzas.inserirPizzas(Margherita);
        Pizzas Pepperoni = new Pizzas("Pepperoni", 53);
        pizzas.inserirPizzas(Pepperoni);
        Pizzas Calabresa = new Pizzas("Calabresa", 55);
        pizzas.inserirPizzas(Calabresa);
        Pizzas Vegetariana = new Pizzas("Vegetariana", 58);
        pizzas.inserirPizzas(Vegetariana);
        Pizzas FrangoComCatupiry = new Pizzas("Frango com Catupiry", 58);
        pizzas.inserirPizzas(FrangoComCatupiry);
        Pizzas Brasileira = new Pizzas("Brasileira", 58);
        pizzas.inserirPizzas(Brasileira);
        Pizzas QuatroQueijos = new Pizzas("Quatro Queijos", 59);
        pizzas.inserirPizzas(QuatroQueijos);
        Pizzas PizzaDoChef = new Pizzas("Pizza do Chef", 61);
        pizzas.inserirPizzas(PizzaDoChef);
        listarPizzas();

    }

    private void listarIngredientes() {

        ArrayList nomeColunas = new ArrayList();
        nomeColunas.add("Nome");
        nomeColunas.add("Valor");

        List<Object[]> dados = new ArrayList<>();

        for (Ingredientes ingredientes : ingredientes.getListaIngredientes()) {

            List dadosIngredientes = new ArrayList();
            dadosIngredientes.add(ingredientes.getNome());
            NumberFormat formatador = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            dadosIngredientes.add(formatador.format(ingredientes.getValor()));

            dados.add(dadosIngredientes.toArray());

        }

        DefaultTableModel tabelaDefault = new DefaultTableModel(dados.toArray(new Object[dados.size()][]), nomeColunas.toArray());
        jTable3.setModel(tabelaDefault);
    }

    private void adicionarIngredientes() {
        Ingredientes MolhoDeTomate = new Ingredientes("Molho de Tomate", 2.50);
        ingredientes.inserirIngredientes(MolhoDeTomate);
        Ingredientes Mussarela = new Ingredientes("Mussarela", 2.50);
        ingredientes.inserirIngredientes(Mussarela);
        Ingredientes ManjericaoFresco = new Ingredientes("Manjericao Fresco", 2.00);
        ingredientes.inserirIngredientes(ManjericaoFresco);
        Ingredientes Pepperoni = new Ingredientes("Pepperoni", 3.00);
        ingredientes.inserirIngredientes(Pepperoni);
        Ingredientes Gorgonzola = new Ingredientes("Gorgonzola", 3.00);
        ingredientes.inserirIngredientes(Gorgonzola);
        Ingredientes Parmesao = new Ingredientes("Parmesao", 3.00);
        ingredientes.inserirIngredientes(Parmesao);
        Ingredientes Provolone = new Ingredientes("Provolone", 3.00);
        ingredientes.inserirIngredientes(Provolone);
        Ingredientes CalabresaFatiada = new Ingredientes("Calabresa Fatiada", 2.00);
        ingredientes.inserirIngredientes(CalabresaFatiada);
        Ingredientes Cebola = new Ingredientes("Cebola", 2.00);
        ingredientes.inserirIngredientes(Cebola);
        Ingredientes Pimentoes = new Ingredientes("Pimentoes", 2.00);
        ingredientes.inserirIngredientes(Pimentoes);
        Ingredientes AzeitonasPretas = new Ingredientes("Azeitonas Pretas", 2.00);
        ingredientes.inserirIngredientes(AzeitonasPretas);
        Ingredientes FrangoDesfiado = new Ingredientes("Frango Desfiado", 3.00);
        ingredientes.inserirIngredientes(FrangoDesfiado);
        Ingredientes Catupiry = new Ingredientes("Catupiry", 3.00);
        ingredientes.inserirIngredientes(Catupiry);
        Ingredientes Milho = new Ingredientes("Milho", 2.00);
        ingredientes.inserirIngredientes(Milho);
        Ingredientes CarneSecaDesfiada = new Ingredientes("Carne-Seca Desfiada", 3.00);
        ingredientes.inserirIngredientes(CarneSecaDesfiada);
        Ingredientes CebolaRoxa = new Ingredientes("Cebola Roxa", 2.00);
        ingredientes.inserirIngredientes(CebolaRoxa);
        listarIngredientes();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_cozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_cozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_cozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_cozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_cozinha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_retornar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel pizza_fachada1;
    private javax.swing.JLabel pizza_fachada2;
    private javax.swing.JLabel pizza_logopequena;
    private javax.swing.JTable tabelaPizzas;
    private javax.swing.JLabel titulo_listaingredientes;
    private javax.swing.JLabel titulo_listapizzas;
    // End of variables declaration//GEN-END:variables
}
