/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaria.interfaces;

import controller.ListaFuncionarios;
import controller.ListaPedidos;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pizzaria.classes.Barista;
import pizzaria.classes.Cozinheiro;
import pizzaria.classes.Entregador;
import pizzaria.classes.Funcionarios;
import pizzaria.classes.Garcom;
import pizzaria.classes.Pedidos;

/**
 *
 * @author usuario
 */
public class interface_areaClientes extends javax.swing.JFrame {

    /**
     * Creates new form interface_areaClientes
     */
    private ListaPedidos pedidos = new ListaPedidos();
    private int linhaSelecionada;

    public interface_areaClientes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        b_retornar = new javax.swing.JButton();
        titulo_listafuncionarios2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jPizzaBox = new javax.swing.JComboBox<>();
        jlNome1 = new javax.swing.JLabel();
        jlNome2 = new javax.swing.JLabel();
        jlNome3 = new javax.swing.JLabel();
        jCheckBorda = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlNome4 = new javax.swing.JLabel();
        jCheckTPp = new javax.swing.JCheckBox();
        jCheckTPg = new javax.swing.JCheckBox();
        jCheckTPm = new javax.swing.JCheckBox();
        jSpinP = new javax.swing.JSpinner();
        jBebidaBox = new javax.swing.JComboBox<>();
        jlNome5 = new javax.swing.JLabel();
        jCheckTBp = new javax.swing.JCheckBox();
        jCheckTBm = new javax.swing.JCheckBox();
        jCheckTBg = new javax.swing.JCheckBox();
        jlNome6 = new javax.swing.JLabel();
        jSpinB = new javax.swing.JSpinner();
        b_cadastrarPedido = new javax.swing.JButton();
        b_atualizarPedido = new javax.swing.JButton();
        b_excluirPedido = new javax.swing.JButton();
        pizza_logopequena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(85, 0, 0));

        b_retornar.setBackground(new java.awt.Color(85, 0, 0));
        b_retornar.setForeground(new java.awt.Color(245, 239, 239));
        b_retornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/saida.png"))); // NOI18N
        b_retornar.setBorderPainted(false);
        b_retornar.setFocusPainted(false);
        b_retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_retornarActionPerformed(evt);
            }
        });

        titulo_listafuncionarios2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        titulo_listafuncionarios2.setForeground(new java.awt.Color(245, 239, 239));
        titulo_listafuncionarios2.setText("Pedidos :");

        jPanel2.setBackground(new java.awt.Color(147, 26, 37));

        jlNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlNome.setForeground(new java.awt.Color(245, 239, 239));
        jlNome.setText("Selecione a Pizza :");

        jPizzaBox.setBackground(new java.awt.Color(233, 113, 113));
        jPizzaBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jPizzaBox.setForeground(new java.awt.Color(245, 239, 239));
        jPizzaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Margherita", "Pepperoni", "Calabresa", "Vegetariana", "Frango com Catupiry", "Quatro Queijos", "Pizza do Chef" }));
        jPizzaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPizzaBoxActionPerformed(evt);
            }
        });

        jlNome1.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jlNome1.setForeground(new java.awt.Color(245, 239, 239));
        jlNome1.setText("Tamanho :");

        jlNome2.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome2.setForeground(new java.awt.Color(245, 239, 239));
        jlNome2.setText("Quantidade :");

        jlNome3.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome3.setForeground(new java.awt.Color(245, 239, 239));
        jlNome3.setText("Com Borda :");

        jCheckBorda.setForeground(new java.awt.Color(147, 26, 37));
        jCheckBorda.setText(".");
        jCheckBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBordaActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(245, 239, 239));
        jTable1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Pedido", "Pizza", "Tamanho", "Quantidade", "Borda", "Bebida", "Tamanho", "Quantidade", "Valor Pedido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlNome4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlNome4.setForeground(new java.awt.Color(245, 239, 239));
        jlNome4.setText("Bebida :");

        jCheckTPp.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPp.setText("P");
        jCheckTPp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPpActionPerformed(evt);
            }
        });

        jCheckTPg.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPg.setText("G");
        jCheckTPg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPgActionPerformed(evt);
            }
        });

        jCheckTPm.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTPm.setText("M");
        jCheckTPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTPmActionPerformed(evt);
            }
        });

        jBebidaBox.setBackground(new java.awt.Color(233, 113, 113));
        jBebidaBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBebidaBox.setForeground(new java.awt.Color(245, 239, 239));
        jBebidaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Cafe", "Refri", "Capuccino", "Cha", "Suco", "Mokha", "Vinho" }));
        jBebidaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBebidaBoxActionPerformed(evt);
            }
        });

        jlNome5.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jlNome5.setForeground(new java.awt.Color(245, 239, 239));
        jlNome5.setText("Tamanho :");

        jCheckTBp.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBp.setText("P");
        jCheckTBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBpActionPerformed(evt);
            }
        });

        jCheckTBm.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBm.setText("M");
        jCheckTBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBmActionPerformed(evt);
            }
        });

        jCheckTBg.setForeground(new java.awt.Color(255, 255, 255));
        jCheckTBg.setText("G");
        jCheckTBg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTBgActionPerformed(evt);
            }
        });

        jlNome6.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jlNome6.setForeground(new java.awt.Color(245, 239, 239));
        jlNome6.setText("Quantidade :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPizzaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTPp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTPm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTPg))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlNome3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBorda))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jlNome4)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBebidaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTBp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTBm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckTBg))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlNome1)
                                    .addComponent(jCheckTPp)
                                    .addComponent(jCheckTPg)
                                    .addComponent(jCheckTPm))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlNome2)
                                    .addComponent(jSpinP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNome3)
                                    .addComponent(jCheckBorda)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPizzaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlNome5)
                                    .addComponent(jCheckTBp)
                                    .addComponent(jCheckTBg)
                                    .addComponent(jCheckTBm))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlNome6)
                                    .addComponent(jSpinB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNome4)
                                .addGap(2, 2, 2)
                                .addComponent(jBebidaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        b_cadastrarPedido.setBackground(new java.awt.Color(233, 113, 113));
        b_cadastrarPedido.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        b_cadastrarPedido.setForeground(new java.awt.Color(245, 239, 239));
        b_cadastrarPedido.setText("Cadastrar");
        b_cadastrarPedido.setBorderPainted(false);
        b_cadastrarPedido.setFocusPainted(false);
        b_cadastrarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_cadastrarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_cadastrarPedidoMouseExited(evt);
            }
        });
        b_cadastrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadastrarPedidoActionPerformed(evt);
            }
        });

        b_atualizarPedido.setBackground(new java.awt.Color(233, 113, 113));
        b_atualizarPedido.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        b_atualizarPedido.setForeground(new java.awt.Color(245, 239, 239));
        b_atualizarPedido.setText("Atualizar");
        b_atualizarPedido.setBorderPainted(false);
        b_atualizarPedido.setFocusPainted(false);
        b_atualizarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_atualizarPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_atualizarPedidoMouseExited(evt);
            }
        });
        b_atualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_atualizarPedidoActionPerformed(evt);
            }
        });

        b_excluirPedido.setBackground(new java.awt.Color(233, 113, 113));
        b_excluirPedido.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        b_excluirPedido.setForeground(new java.awt.Color(245, 239, 239));
        b_excluirPedido.setText("Deletar");
        b_excluirPedido.setBorderPainted(false);
        b_excluirPedido.setFocusPainted(false);
        b_excluirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_excluirPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_excluirPedidoMouseExited(evt);
            }
        });
        b_excluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_excluirPedidoActionPerformed(evt);
            }
        });

        pizza_logopequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaria.icons/pizza_logo_pequena.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pizza_logopequena)
                        .addGap(262, 262, 262)
                        .addComponent(titulo_listafuncionarios2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_retornar)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_cadastrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_atualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(b_excluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizza_logopequena)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(b_retornar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(titulo_listafuncionarios2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cadastrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_atualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_excluirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_retornarActionPerformed
        interface_entrada i_entrada = new interface_entrada();
        i_entrada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_retornarActionPerformed

    private void b_cadastrarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoMouseEntered
        b_cadastrarPedido.setBackground(new Color(233, 143, 143));
    }//GEN-LAST:event_b_cadastrarPedidoMouseEntered

    private void b_cadastrarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoMouseExited
        b_cadastrarPedido.setBackground(new Color(233, 113, 113));
    }//GEN-LAST:event_b_cadastrarPedidoMouseExited

    private void b_cadastrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadastrarPedidoActionPerformed
        switch(jPizzaBox.getSelectedItem().equals()){
            
        }

    }//GEN-LAST:event_b_cadastrarPedidoActionPerformed

    private void b_atualizarPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_atualizarPedidoMouseEntered
        b_atualizarPedido.setBackground(new Color(233, 143, 143));
    }//GEN-LAST:event_b_atualizarPedidoMouseEntered

    private void b_atualizarPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_atualizarPedidoMouseExited
        b_atualizarPedido.setBackground(new Color(233, 113, 113));
    }//GEN-LAST:event_b_atualizarPedidoMouseExited

    private void b_atualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_atualizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_atualizarPedidoActionPerformed

    private void b_excluirPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_excluirPedidoMouseEntered
        b_excluirPedido.setBackground(new Color(233, 143, 143));
    }//GEN-LAST:event_b_excluirPedidoMouseEntered

    private void b_excluirPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_excluirPedidoMouseExited
        b_excluirPedido.setBackground(new Color(233, 113, 113));
    }//GEN-LAST:event_b_excluirPedidoMouseExited

    private void b_excluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_excluirPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_excluirPedidoActionPerformed

    private void jPizzaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPizzaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPizzaBoxActionPerformed

    private void jCheckTPpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPpActionPerformed
        if (jCheckTPp.isSelected()) {
            jCheckTPg.setSelected(false);
            jCheckTPm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTPpActionPerformed

    private void jCheckTPgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPgActionPerformed
        if (jCheckTPg.isSelected()) {
            jCheckTPp.setSelected(false);
            jCheckTPm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTPgActionPerformed

    private void jCheckTPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTPmActionPerformed
        if (jCheckTPm.isSelected()) {
            jCheckTPp.setSelected(false);
            jCheckTPg.setSelected(false);
        }

    }//GEN-LAST:event_jCheckTPmActionPerformed

    private void jCheckBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBordaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBordaActionPerformed

    private void jBebidaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBebidaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBebidaBoxActionPerformed

    private void jCheckTBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBpActionPerformed
        if (jCheckTBp.isSelected()) {
            jCheckTBm.setSelected(false);
            jCheckTBg.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBpActionPerformed

    private void jCheckTBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBmActionPerformed
        if (jCheckTBm.isSelected()) {
            jCheckTBp.setSelected(false);
            jCheckTBg.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBmActionPerformed

    private void jCheckTBgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTBgActionPerformed
        if (jCheckTBg.isSelected()) {
            jCheckTBp.setSelected(false);
            jCheckTBm.setSelected(false);
        }
    }//GEN-LAST:event_jCheckTBgActionPerformed

    private void listarPedidos() {

        ArrayList nomeColunas = new ArrayList();
        nomeColunas.add("N° Pedido");
        nomeColunas.add("Pizza");
        nomeColunas.add("Tamanho");
        nomeColunas.add("Quantidade");
        nomeColunas.add("Borda");
        nomeColunas.add("Bebida");
        nomeColunas.add("Tamanho");
        nomeColunas.add("Quantidade");
        nomeColunas.add("Valor Pedido");

        List<Object[]> dados = new ArrayList<>();

        for (Pedidos pedidos : pedidos.getListaPedidos()) {

            List dadosCli = new ArrayList();
            dadosCli.add(pedidos.getNumPedidos());
            dadosCli.add(pedidos.getPizzaPedidos());
            dadosCli.add(pedidos.getPizzaPedidos().getTamanho());
            dadosCli.add(pedidos.getPizzaPedidos().getQuantidade());
            dadosCli.add(pedidos.getPizzaPedidos().isBorda());
            dadosCli.add(pedidos.getBebidaPedidos());
            dadosCli.add(pedidos.getBebidaPedidos().getTamanho());
            dadosCli.add(pedidos.getBebidaPedidos().getQuantidade());
            dadosCli.add(pedidos.getValorPedidos());

            dados.add(dadosCli.toArray());

        }

        DefaultTableModel tabelaDefault = new DefaultTableModel(dados.toArray(new Object[dados.size()][]), nomeColunas.toArray());
        jTable1.setModel(tabelaDefault);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_areaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_areaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_atualizarPedido;
    private javax.swing.JButton b_cadastrarPedido;
    private javax.swing.JButton b_excluirPedido;
    private javax.swing.JButton b_retornar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> jBebidaBox;
    private javax.swing.JCheckBox jCheckBorda;
    private javax.swing.JCheckBox jCheckTBg;
    private javax.swing.JCheckBox jCheckTBm;
    private javax.swing.JCheckBox jCheckTBp;
    private javax.swing.JCheckBox jCheckTPg;
    private javax.swing.JCheckBox jCheckTPm;
    private javax.swing.JCheckBox jCheckTPp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jPizzaBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinB;
    private javax.swing.JSpinner jSpinP;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlNome2;
    private javax.swing.JLabel jlNome3;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel pizza_logopequena;
    private javax.swing.JLabel titulo_listafuncionarios2;
    // End of variables declaration//GEN-END:variables
}
